### ISSUE TITLE
Comments still showing with the full width template

### ISSUE THREAD

**Issue by reachadam** [brainstormforce/fullwidth-templates#16]
I installed the plugin, added the full width template to a page, when viewing the page the comments section is showing full width. 

I think full width should also eliminate comments OR the comments should be in the theme container, not full width, then rely on WP to disable them.

**Comment by Nikschavan** [comment]
I actually brought this functionality [in as a feature](https://github.com/brainstormforce/fullwidth-templates/issues/13) But now that I think about it, this does not look good on full-width templates.

I think we can fully remove the comment form for full-width templates and only keep it for the template "No sidebar".

The comment form can be controlled by WordPress options by disabling the comment form from the [page meta options](http://screenshots.sharkz.in/nik/screenshots/20170301191112.jpg)

**Comment by Nikschavan** [comment]
Hey @reachadam I'll close this issue now, you can still comment any feedback you have on this :)
