### ISSUE TITLE
Readme.txt description

### ISSUE THREAD

**Issue by sujaypawar** [brainstormforce/fullwidth-templates#5]
- What does this plugin do?
- Who is this useful for?
- Use Examples
-- Page Builders
-- Landing Pages

References - 
https://premium.wpmudev.org/blog/create-full-width-page/

**Comment by sujaypawar** [comment]
Full Width Page Template for Any WordPress Theme

Doesn't your theme offer full width page templates?
Need freedom to design beautiful full width layouts with page builder like Beaver Builder, Elementor?
Need a complete blank template without header or footer for your landing pages?

This plugins adds three new templates for you to help with above challenges.

- Full Width Template
- Blank Template (Without Header Footer)
- No Sidebar Template (Just Removes Sidebar)

**Comment by Nikschavan** [comment]
@sujaypawar updated the readme, have a look!

**Comment by Nikschavan** [comment]
Updated the readme further in https://github.com/brainstormforce/fullwidth-templates/issues/31
