### ISSUE TITLE
Plugin not responding correctly.

### ISSUE THREAD

**Issue by 1niteonly** [brainstormforce/fullwidth-templates#53]
I am using the xPerson Lite theme for word press. I can load up the plugin fine and choose between the options. However, when the page loads everything is aligned to the left, instead of being centered like it is in the text field. The theme apparently has no sidebar on the home page. What I'm trying to do is remove the sidebar space so my content can be directly in the center instead of off centered to the left. The plugin unexpectedly pushed everything far lefter.  Here is an image of what happened. 
![image](https://user-images.githubusercontent.com/31718623/30145223-eb7b04c4-935d-11e7-8b73-0ea9136781ee.png)

One of the page of my website having the issue is http://www.dontcursekids.com/tunes/. Any help would be appreciated.

**Comment by Nikschavan** [comment]
Hello @1niteonly,

The iframe you have added needs some more CSS to align it in the center.

Just add this custom CSS and the iframe should be aligned to center -
```
.frame_outer {
    margin-left: auto;
    margin-right: auto;
}
```

**Comment by 1niteonly** [comment]
thank you so much
