### ISSUE TITLE
No SideBar .... No BreadCrumbs Help....

### ISSUE THREAD

**Issue by CodeTazMan** [brainstormforce/fullwidth-templates#73]
Hello,

I hope that you are doing well in this current crisis.

I am using a plugin: https://wordpress.org/plugins/fullwidth-templates/ 

You can see the page using the NO SIDEBAR option here:  https://wholesale-nutraceuticals.com/private-label-sexual-enhancement-supplement-for-women/

A page that does have the BreadCrumbs on it is here: https://wholesale-nutraceuticals.com/wholesale-private-label-b-vitamin-supplements/

and I am using the NO SIDEBAR option.  It seems that it strips out a lot of code, including the the Mantra BreadCrumb option. The BreadCrumb option is enabled in the Theme Option and works or the rest of the site, but not the pages using the NO SIDEBAR option.

I would like to know if there is a way that I could manually add back the code to display the Mantra BreadCrumbs by adding some php directly to the page or editing the Mantra Child Theme function.php to apply the Mantra BreadCrumbs to the pages where I use the fullwidth-template with the NO SIDEBAR option

Thank you for your attention.

**Comment by sujaypawar** [comment]
Hi @CodeTazMan - It seems that your theme might not be compatible with the "fullwidth templates" plugin.

We will try to see if we can add compatibility for it if there are more user requests. But until then, there is no easy solution that we can offer you.

I'm sorry as I understand this wasn't the answer you were hoping for.

**Comment by CodeTazMan** [comment]
Thanks for your response, I have devised a WorkAround for the BreadCrumb issue.
I used function located here>> https://www.codexworld.com/wordpress-how-to-display-breadcrumb-without-plugin/   
But I implemented through a PHP plugin :  https://wordpress.org/plugins/my-custom-functions/
and now I have breadcrumbs again, maybe someone will find this useful for other issues.
