### ISSUE TITLE
Add a Prefix to the template names

### ISSUE THREAD

**Issue by sujaypawar** [brainstormforce/fullwidth-templates#8]
A prefix will help new templates easily recognizable. Right now, they get mixed with theme / other templates so recognizing the ones added by this plugin is difficult.

Further - the names we have now, are long. Short ones like these will be better IMO - 

- BSF Blank
- BSF Fullwidth
- BSF No Sidebar

**Comment by sujaypawar** [comment]
https://cloudup.com/cY68iOrDrrm

Page Template suffix can be removed

**Comment by sujaypawar** [comment]
BSF Prefix does not feel relevant. We need to fix an alternative.

**Comment by reachadam** [comment]
How about:
FW Blank
FW Normal
FW Comments

etc......

**Comment by sujaypawar** [comment]
FW looks good!

**Comment by Nikschavan** [comment]
Finalizing these - 

```FW No Sidebar
FW Fullwidth
FW Fullwidth No Header Footer```
